- name: git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
  command: git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build creates=~/.rbenv/plugins/ruby-build/
  tags:
    - ruby
    - ruby-build
